# Generated by Django 5.2.17 on 2026-09-17 11:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(db_index=True, max_length=20)),
                ('flight_number', models.CharField(max_length=30)),
                ('route_origin', models.CharField(max_length=100)),
                ('route_destination', models.CharField(max_length=100)),
                ('flight_date', models.DateField()),
                ('scheduled_departure', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ON_TIME', 'On Time'), ('CANCELLED', 'Cancelled'), ('DELAYED', 'Delayed'), ('UNAFFECTED', 'Unaffected')], default='ON_TIME', max_length=30)),
                ('delay_hours', models.FloatField(default=0.0)),
                ('new_departure', models.CharField(blank=True, max_length=20, null=True)),
                ('disruption_reason', models.TextField(blank=True, default='')),
                ('is_return', models.BooleanField(default=False)),
                ('original_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(default='Original Card / UPI', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['flight_date', 'scheduled_departure'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('loyalty_tier', models.CharField(choices=[('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='SILVER', max_length=20)),
                ('booking_reference', models.CharField(db_index=True, max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('travel_history', models.TextField(blank=True, default='')),
                ('prior_complaints', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyKnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('rule_text', models.TextField()),
                ('is_agent_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated')], default='ACTIVE', max_length=30)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='resolution_agent.booking')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='resolution_agent.customer')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='resolution_agent.customer'),
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('BEYOND_POLICY_COMPENSATION', 'Compensation Beyond Stated Policy Amounts'), ('FARE_WAIVER_EXCEEDS_1500', 'Fare Difference Waiver Exceeds ₹1,500'), ('NON_AIRLINE_DISRUPTION', 'Non-Airline Caused Disruption Exception'), ('LEGAL_OR_FORMAL_COMPLAINT', 'Threats of Legal Action or Formal Complaints'), ('NON_ORIGINAL_PAYMENT_REFUND', 'Refund to Different Payment Method Requested'), ('SUPERVISOR_INTERVENTION', 'Supervisor Intervention Needed')], max_length=60)),
                ('prohibited_action_attempted', models.TextField()),
                ('supervisor_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Supervisor Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved by Supervisor'), ('REJECTED', 'Rejected by Supervisor')], default='PENDING', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='HIGH', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations', to='resolution_agent.booking')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='resolution_agent.conversation')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='resolution_agent.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('CUSTOMER', 'Customer'), ('AGENT', 'Agent'), ('SYSTEM', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('intent', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='resolution_agent.conversation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('FULL_REFUND', 'Full Refund (Original Payment Method, 7 Business Days)'), ('FREE_REBOOKING_24H', 'Free Rebooking within 24 Hours'), ('PRIORITY_REBOOKING', 'Priority Rebooking (Gold/Platinum First Access)'), ('MEAL_VOUCHER_500', '₹500 Meal Voucher'), ('MEAL_VOUCHER_AND_LOUNGE', 'Meal Voucher + Lounge Access'), ('MEAL_AND_HOTEL_DELAYED_HOURS', 'Meal Voucher + Hotel for Delayed Hours Only'), ('FARE_DIFFERENCE_WAIVER', 'Fare Difference Waiver (<= ₹1,500)'), ('EXPLANATION_ONLY', 'Policy Explanation / Status Provided'), ('DENIED', 'Request Denied Under Policy')], max_length=60)),
                ('status', models.CharField(choices=[('OFFERED', 'Offered'), ('ACCEPTED', 'Accepted'), ('PROCESSED', 'Processed'), ('DENIED', 'Denied')], default='PROCESSED', max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reference_code', models.CharField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolutions', to='resolution_agent.booking')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='resolution_agent.conversation')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='resolution_agent.customer')),
            ],
        ),
    ]
